# Generated by Django 5.2.1 on 2025-05-18 18:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_latlng', models.CharField(max_length=50)),
                ('dropoff_latlng', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending pickup'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=15)),
                ('courier_tracking', models.CharField(blank=True, max_length=255)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='donations.donation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
