# Generated by Django 5.2.1 on 2025-05-18 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='courier_tracking',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='is_active',
        ),
        migrations.AddField(
            model_name='delivery',
            name='distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='duration_s',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='polyline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='donation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donations.donation'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in_transit', 'in_transit'), ('delivered', 'delivered')], default='pending', max_length=20),
        ),
    ]
