services:
  db:
    image: mysql:8.4
    container_name: hope_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hopeconnect
      MYSQL_USER: hopeuser
      MYSQL_PASSWORD: hopepass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  redis:
    image: redis:7
    container_name: hope_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  django:
    build: .
    container_name: hope_django
    command: /entrypoint.sh
    environment:
      SERVICE: django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env

  celery_worker:
    build: .
    container_name: hope_celery_worker
    command: /entrypoint.sh
    environment:
      SERVICE: celery_worker
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery_beat:
    build: .
    container_name: hope_celery_beat
    command: /entrypoint.sh
    environment:
      SERVICE: celery_beat
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  mysql_data:
