# Generated by Django 5.2.1 on 2025-05-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrequest',
            name='required_skills',
            field=models.TextField(default='UNDEFINED'),
        ),
    ]
