# Generated by Django 5.2.1 on 2025-05-23 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orphanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('verification_doc', models.FileField(blank=True, upload_to='verification/')),
                ('is_public_approved', models.BooleanField(default=False)),
                ('manager', models.OneToOneField(limit_choices_to={'role': 'ORPHANAGE'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrphanageNeedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedding', models.TextField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_requests', to='orphanages.orphanage')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(limit_choices_to={'role': 'DONOR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orphanages.orphanage')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('orphanage', 'donor')},
            },
        ),
    ]
