# Generated by Django 5.2.1 on 2025-05-18 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanage',
            name='is_public_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrphanUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='orphan_updates/')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='orphanages.orphan')),
            ],
        ),
    ]
