# Generated by Django 5.2.1 on 2025-05-18 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanages', '0002_orphanage_is_public_approved_orphanupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(limit_choices_to={'role': 'DONOR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orphanages.orphanage')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('orphanage', 'donor')},
            },
        ),
    ]
