# Generated by Django 5.2.1 on 2025-05-23 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('orphan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('donation_category', models.CharField(choices=[('GENERAL', 'General'), ('EDUCATION', 'Education'), ('MEDICAL', 'Medical'), ('MONEY', 'Money')], default='MONEY', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('donation_type', models.CharField(choices=[('ORPHAN', 'Orphan'), ('CAMPAIGN', 'Campaign')], default='ORPHAN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='campaigns.campaign')),
                ('donor', models.ForeignKey(limit_choices_to={'role': 'DONOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('orphan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='orphan.orphan')),
            ],
        ),
        migrations.CreateModel(
            name='EducationDonation',
            fields=[
                ('donation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='donations.donation')),
                ('field', models.CharField(blank=True, max_length=255)),
                ('course', models.CharField(blank=True, max_length=255)),
                ('course_duration', models.PositiveIntegerField(default=1)),
                ('hours_per_week', models.PositiveIntegerField(default=1)),
            ],
            bases=('donations.donation',),
        ),
        migrations.CreateModel(
            name='GeneralDonation',
            fields=[
                ('donation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='donations.donation')),
                ('description', models.TextField(blank=True)),
                ('material', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('need_transportation', models.BooleanField(default=False)),
            ],
            bases=('donations.donation',),
        ),
        migrations.CreateModel(
            name='MedicalDonation',
            fields=[
                ('donation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='donations.donation')),
                ('supply_type', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
            ],
            bases=('donations.donation',),
        ),
        migrations.CreateModel(
            name='MoneyDonation',
            fields=[
                ('donation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='donations.donation')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_for', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255)),
            ],
            bases=('donations.donation',),
        ),
        migrations.CreateModel(
            name='DonationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='donations.donation')),
            ],
        ),
    ]
