# Generated by Django 5.2.1 on 2025-05-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('EDUCATION', 'Education'), ('MEDICAL', 'Medical'), ('EMERGENCY', 'Emergency'), ('MONEY', 'Money'), ('PHYSICAL', 'Physical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('EDUCATION', 'Education'), ('MEDICAL', 'Medical'), ('EMERGENCY', 'Emergency'), ('MONEY', 'Money'), ('PHYSICAL', 'Physical')], max_length=20),
        ),
    ]
