# Generated by Django 5.2.1 on 2025-05-23 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orphanages', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orphan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=14, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('health_info', models.TextField(blank=True)),
                ('education_status', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='orphans/%Y/%m')),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orphans', to='orphanages.orphanage')),
            ],
        ),
        migrations.CreateModel(
            name='OrphanUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='orphan_updates/')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='orphan.orphan')),
            ],
        ),
        migrations.CreateModel(
            name='OrphanSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(limit_choices_to={'role': 'DONOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='sponsorships', to=settings.AUTH_USER_MODEL)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='orphan.orphan')),
            ],
            options={
                'unique_together': {('orphan', 'donor')},
            },
        ),
    ]
