# Generated by Django 5.2.1 on 2025-05-23 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orphanages', '__first__'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('need_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanages.orphanageneedrequest')),
                ('volunteer_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteerofferrequest')),
            ],
        ),
    ]
