# Generated by Django 5.2.1 on 2025-05-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('general', 'General'), ('emergency', 'Emergency')], max_length=20)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
